name: Java Practice CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Determine Changed Modules
        id: changed-files
        run: |
          CHANGED_MODULE=$(git diff --name-only HEAD^ HEAD | grep -o '^[^/]*/' | sort -u | head -n 1)
          echo "changed_module=$CHANGED_MODULE" >> $GITHUB_ENV
      - name: Build with Maven
        run: mvn package -pl ${CHANGED_MODULE} -am